version: '2'
services:
  eureka:
    image: springcloud/eureka
    container_name: eureka
    hostname: eureka
    network_mode: host
    ports:
      - "8761:8761"
  rabbitmq:
    image: rabbitmq:3.6.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - TZ=America/Sao_Paulo
  postgres:
    image: postgres:9.6-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sacdb
      - TZ=America/Sao_Paulo
    container_name: postgres