version: '2'
services:
  eureka:
   image: raphacps/eureka
   container_name: eureka
   hostname: eureka   
   ports:
     - "8761:8761"
  edge-server:
    image: raphacps/edge-server
    hostname: edge-server
    network_mode: host
    ports:
      - "8080:8080"
    container_name: edge-server
    depends_on:
      - eureka
  rabbitmq:
    image: rabbitmq:3.6.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - TZ=America/Sao_Paulo
  postgres:
    image: postgres:9.6-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sacdb
      - TZ=America/Sao_Paulo
    container_name: postgres
  sac-command:
    image: raphacps/sac-command:v1.0.0
    container_name: sac-command
    network_mode: host
